{% set name = "ast-grep" %}
{% set version = "0.39.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 6a8665ce5105920fdff5e972e37ffc3cba7b0fe6f3eff9bb05fa06ce778e077d

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
    - {{ stdlib("c") }}
    - cargo-bundle-licenses

test:
  commands:
    - sg --version
    - ast-grep --version

about:
  home: https://github.com/ast-grep/ast-grep
  summary: 'ast-grep(sg) is a CLI tool for code structural search, lint, and rewriting.'
  description: |
    ast-grep is an AST-based tool to search code by pattern code. Think it as
    your old-friend grep but it matches AST nodes instead of text. You can
    write patterns as if you are writing ordinary code. It will match all code
    that has the same syntactical structure. You can use $ sign + upper case
    letters as wildcard, e.g. $MATCH, to match any single AST node. Think it as
    REGEX dot ., except it is not textual.
  license: MIT
  license_file:
    - THIRDPARTY.yml
    - LICENSE
  doc_url: https://ast-grep.github.io/
  dev_url: https://github.com/ast-grep/ast-grep

extra:
  recipe-maintainers:
    - asford
    - danielnachun
    - moritzwilksch
